import { DataSource } from "typeorm"
import { env } from "@/env"
import { app } from "@/app"
import { Product } from "@/entities/product.entity"
import { Category } from "@/entities/category.entity"
import { ProductAutoGeneratedUUID1764778336051 } from "@/lib/typeorm/migrations/1764778336051-ProductAutoGeneratedUUID"

export const AppDataSource = new DataSource({
    type: "postgres",
    host: env.DATABASE_HOST,
    port: Number(env.DATABASE_PORT),
    username: env.DATABASE_USER,
    password: env.DATABASE_PASSWORD,
    database: env.DATABASE_NAME,
    entities: [Product, Category],
    migrations: [ProductAutoGeneratedUUID1764778336051],
    logging: env.NODE_ENV === 'development',
})

AppDataSource
    .initialize()
    .then(() => { 
        console.log("Database with typeorm connected!")
    })
    .catch((error) => {
        console.error("Error connecting to database with typeorm", error)
        app.close()
    })